//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlCenter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ControlCenter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GTASACarPics {
            get {
                object obj = ResourceManager.GetObject("GTASACarPics", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GTASACheats {
            get {
                object obj = ResourceManager.GetObject("GTASACheats", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GTASAConfig {
            get {
                object obj = ResourceManager.GetObject("GTASAConfig", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Main]
        ///ReadMe=All settings are kept in this ini to keep Registry Clean
        ///Interval=50
        ///Feedback=1
        ///GTASAVersion=v1.1
        ///InfoMsg=0
        ///OrgSCM=1
        ///SafeCheats=1
        ///Fireproof=0,1
        ///InfiniteRun=0,1
        ///NeverWanted=1,1
        ///InfAmmo=1,1
        ///NeverHungry=1,1
        ///TankCheat=0,0
        ///InfHealth=1,1
        ///InfOxygen=0,0
        ///MegaJump=0,0
        ///MaxSexAppeal=0,0
        ///CheapCars=0,0
        ///FastCars=0,0
        ///MaxRespect=0,0
        ///MegaPunch=0,0
        ///BoatsFly=0,0
        ///CarsFly=0,0
        ///Weather=0,10
        ///OneHitKill=0,1
        ///FreezeTimers=0,0
        ///
        ///[PlayerTracking]
        ///FixArmor=1,400
        ///FixHealth=1,400
        ///FixWanted=0,0
        ///F [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GTASAConsole {
            get {
                return ResourceManager.GetString("GTASAConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GTASAData {
            get {
                object obj = ResourceManager.GetObject("GTASAData", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GTASALocs {
            get {
                object obj = ResourceManager.GetObject("GTASALocs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon unlocked {
            get {
                object obj = ResourceManager.GetObject("unlocked", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
