//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlCenter.Infrastructure.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ControlCenter.Infrastructure.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GTASACarPics {
            get {
                object obj = ResourceManager.GetObject("GTASACarPics", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;encoding=&quot;UTF-8&quot;standalone=&quot;yes&quot;?&gt;
        ///&lt;CarPics&gt;
        ///	&lt;CarPic CarID=&quot;506&quot; TypeID=&quot;0&quot; CarName=&quot;Super GT&quot; Stars=&quot;5&quot; Description=&quot;A great looking car and quick too. But it&apos;s a bit of a handful at times and tricky to handle at high speed. Not recommended for a high pursuit&quot;/&gt;
        ///	&lt;CarPic CarID=&quot;541&quot; TypeID=&quot;0&quot; CarName=&quot;Bullet&quot; Stars=&quot;5&quot; Description=&quot;Awesome car. Looks stunning&quot;/&gt;
        ///	&lt;CarPic CarID=&quot;579&quot; TypeID=&quot;0&quot; CarName=&quot;Huntley&quot; Stars=&quot;5&quot; Description=&quot;The huntley is a superb 4x4 that looks great too [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GTASACarPics1 {
            get {
                return ResourceManager.GetString("GTASACarPics1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Cars&gt;
        ///    &lt;Car ID=&quot;445&quot; CarName=&quot;Admiral&quot; Type=&quot;car&quot; Dim.X=&quot;200&quot; Dim.Y=&quot;490&quot; Dim.Z=&quot;150&quot; hHandling=&quot;400000&quot; isParkable=&quot;1&quot; MinorColor=&quot;34&quot; MajorColor=&quot;34&quot; AllowedModifications=&quot;3F0;3F1;3F2;43E;43F&quot;/&gt;
        ///    &lt;Car ID=&quot;602&quot; CarName=&quot;Alpha&quot; Type=&quot;car&quot; Dim.X=&quot;200&quot; Dim.Y=&quot;500&quot; Dim.Z=&quot;200&quot; hHandling=&quot;200000&quot; isParkable=&quot;1&quot; MinorColor=&quot;58&quot; MajorColor=&quot;1&quot; AllowedModifications=&quot;3F0;3F1;3F2;43E;43F&quot;/&gt;
        ///    &lt;Car ID=&quot;416&quot; CarName=&quot;Ambulance&quot; Type=&quot;car&quot; Dim.X=&quot;220&quot; Dim.Y=&quot;650&quot; Dim. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GTASACars {
            get {
                return ResourceManager.GetString("GTASACars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;CarTypes&gt;
        ///    &lt;CarType ID=&quot;0&quot; Name=&quot;Favorites&quot;/&gt;
        ///    &lt;CarType ID=&quot;1&quot; Name=&quot;Sports Cars&quot;/&gt;
        ///    &lt;CarType ID=&quot;2&quot; Name=&quot;Off-road&quot;/&gt;
        ///    &lt;CarType ID=&quot;3&quot; Name=&quot;Lowriders&quot;/&gt;
        ///    &lt;CarType ID=&quot;4&quot; Name=&quot;Convertibles&quot;/&gt;
        ///    &lt;CarType ID=&quot;5&quot; Name=&quot;Other Cars&quot;/&gt;
        ///    &lt;CarType ID=&quot;6&quot; Name=&quot;Industrial Vehicles&quot;/&gt;
        ///    &lt;CarType ID=&quot;7&quot; Name=&quot;Public Service&quot;/&gt;
        ///    &lt;CarType ID=&quot;8&quot; Name=&quot;Helicopters&quot;/&gt;
        ///    &lt;CarType ID=&quot;9&quot; Name=&quot;Planes&quot;/&gt;
        ///    &lt;CarType ID=&quot;10&quot; Nam [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GTASACarTypes {
            get {
                return ResourceManager.GetString("GTASACarTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GTASACheats {
            get {
                object obj = ResourceManager.GetObject("GTASACheats", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Locations&gt;
        ///	&lt;Location UID=&quot;2608DD1D-5704-F841-85E5-4EDCC39226A5&quot; Folder=&quot;GTA SA Cheats\Gameplay&quot; CheatString=&quot;CPKTNWT&quot; Description=&quot;Blow Up All Cars&quot;/&gt;
        ///	&lt;Location UID=&quot;1D229A75-9642-4747-967F-42F712BCC8E8&quot; Folder=&quot;GTA SA Cheats\Gameplay&quot; CheatString=&quot;HESOYAM&quot; Description=&quot;Health Armor $250k&quot;/&gt;
        ///	&lt;Location UID=&quot;53AEB036-6BB9-3F49-9172-551CCF904466&quot; Folder=&quot;GTA SA Cheats\Gameplay&quot; CheatString=&quot;SJMAHPE&quot; Description=&quot;Recruit Anyone (9mm)&quot;/&gt;
        ///	&lt;Location [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GTASACheats1 {
            get {
                return ResourceManager.GetString("GTASACheats1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Colors&gt;
        ///  &lt;Color Rgb=&quot;0,0,0&quot; ID=&quot;0&quot; ToolTip=&quot;black&quot; /&gt;
        ///  &lt;Color Rgb=&quot;245,245,245&quot; ID=&quot;1&quot; ToolTip=&quot;white&quot; /&gt;
        ///  &lt;Color Rgb=&quot;42,119,161&quot; ID=&quot;2&quot; ToolTip=&quot;police car blue&quot; /&gt;
        ///  &lt;Color Rgb=&quot;132,4,16&quot; ID=&quot;3&quot; ToolTip=&quot;cherry red&quot; /&gt;
        ///  &lt;Color Rgb=&quot;38,55,57&quot; ID=&quot;4&quot; ToolTip=&quot;mIDnight blue&quot; /&gt;
        ///  &lt;Color Rgb=&quot;134,68,110&quot; ID=&quot;5&quot; ToolTip=&quot;temple curtain purple&quot; /&gt;
        ///  &lt;Color Rgb=&quot;215,142,16&quot; ID=&quot;6&quot; ToolTip=&quot;taxi yellow&quot; /&gt;
        ///  &lt;Color Rgb=&quot;76,117,183&quot; ID=&quot;7&quot; ToolTip=&quot;striking blu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GTASAColors {
            get {
                return ResourceManager.GetString("GTASAColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GTASAConfig {
            get {
                object obj = ResourceManager.GetObject("GTASAConfig", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Main]
        ///ReadMe=All settings are kept in this ini to keep Registry Clean
        ///Interval=50
        ///Feedback=1
        ///GTASAVersion=v1.1
        ///InfoMsg=0
        ///OrgSCM=1
        ///SafeCheats=1
        ///Fireproof=0,1
        ///InfiniteRun=0,1
        ///NeverWanted=1,1
        ///InfAmmo=1,1
        ///NeverHungry=1,1
        ///TankCheat=0,0
        ///InfHealth=1,1
        ///InfOxygen=0,0
        ///MegaJump=0,0
        ///MaxSexAppeal=0,0
        ///CheapCars=0,0
        ///FastCars=0,0
        ///MaxRespect=0,0
        ///MegaPunch=0,0
        ///BoatsFly=0,0
        ///CarsFly=0,0
        ///Weather=0,10
        ///OneHitKill=0,1
        ///FreezeTimers=0,0
        ///
        ///[PlayerTracking]
        ///FixArmor=1,400
        ///FixHealth=1,400
        ///FixWanted=0,0
        ///F [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GTASAConsole {
            get {
                return ResourceManager.GetString("GTASAConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GTASAData {
            get {
                object obj = ResourceManager.GetObject("GTASAData", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Locations&gt;
        ///	&lt;Location UID=&quot;64EFF8C6-E20E-8C4B-ACFC-1895B23C0EEF&quot; Folder=&quot;GTA SA Locations\Flowers&quot; Description=&quot;Flower 01&quot; LocationData=&quot;1928.68;-1774.21;13.54;90&quot;/&gt;
        ///	&lt;Location UID=&quot;263A5859-51F8-2541-B515-2B00123ED5B9&quot; Folder=&quot;GTA SA Locations\Flowers&quot; Description=&quot;Flower 02&quot; LocationData=&quot;1875.91;-1917.18;15.03;90&quot;/&gt;
        ///	&lt;Location UID=&quot;4DCC5450-50D6-BB44-BE3A-BF0834B13AAF&quot; Folder=&quot;GTA SA Locations\Flowers&quot; Description=&quot;Flower 03&quot; LocationData=&quot;2019 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GTASALocations {
            get {
                return ResourceManager.GetString("GTASALocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GTASALocs {
            get {
                object obj = ResourceManager.GetObject("GTASALocs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Shortcuts&gt;
        ///    &lt;Shortcut UID=&quot;B1B9B667-1128-4541-A46A-6778D91F67F1&quot; Folder=&quot;GTA SA Shortcuts\Driving Help&quot; Description=&quot;1 Flight Assistance: (ON)&quot; Active=&quot;1&quot; ComboText=&quot;1&quot; ExtKeyCode=&quot;0&quot; KeyCode=&quot;49&quot; Category=&quot;0&quot; Command=&quot;56&quot; DataPage=&quot;16&quot; AdditionData=&quot;1&quot; Explanation=&quot;(ON)&quot;/&gt;
        ///    &lt;Shortcut UID=&quot;6642562D-466F-4E4F-98BB-D3F906AE62CE&quot; Folder=&quot;GTA SA Shortcuts\Driving Help&quot; Description=&quot;2 Flight Assistance: (OFF)&quot; Active=&quot;1&quot; ComboText=&quot;2&quot; ExtKeyCode=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GTASAShortcuts {
            get {
                return ResourceManager.GetString("GTASAShortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Weapons&gt;
        ///    &lt;Weapon Name=&quot;Knife&quot; Category=&quot;Melee Weapons&quot;/&gt;
        ///    &lt;Weapon Name=&quot;Nightstick&quot; Category=&quot;Melee Weapons&quot;/&gt;
        ///    &lt;Weapon Name=&quot;Pool Cue&quot; Category=&quot;Melee Weapons&quot;/&gt;
        ///    &lt;Weapon Name=&quot;Golf Club&quot; Category=&quot;Melee Weapons&quot;/&gt;
        ///    &lt;Weapon Name=&quot;Baseball Bat&quot; Category=&quot;Melee Weapons&quot;/&gt;
        ///    &lt;Weapon Name=&quot;Shovel&quot; Category=&quot;Melee Weapons&quot;/&gt;
        ///    &lt;Weapon Name=&quot;Katana&quot; Category=&quot;Melee Weapons&quot;/&gt;
        ///    &lt;Weapon Name=&quot;Chainsaw&quot; Category=&quot;Melee Weapons&quot;/&gt;
        ///    &lt;Weapon N [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GTASAWeapons {
            get {
                return ResourceManager.GetString("GTASAWeapons", resourceCulture);
            }
        }
    }
}
